#!/bin/bash

set -e
name=$(basename $0)_$(uuidgen)
set +e

docker run --name $name \
	   -v $(pwd):/src \
           -v /var/cache/pacman/pkg:/var/cache/pacman/pkg \
           -v /etc/makepkg.conf:/etc/makepkg.conf \
           justin8/makepkg $@

docker rm $name
